# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c371b062faffd2915f46b568b8fd45fa1745ee828c931ca5d9bd2aa0e9a91c5c0a2da63bb8cb3cd018f0e956e6013c4e9b9278a9bf6f3763a766926bb7d694b

test:
  secret_key_base: 6287231751b6b5a857e9a90c0dd162d5f018fc88af3d768ece182da963b45e9b8b29e41a1257ede47a8babc2aa751c81069bef5faeba2188c4d2a1d93aec84ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
